### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JelleHissink** [AchievedOwner/BlamanticUI#1]
Hello, 

We have been looking for a fomantic-ui component library for blazor. We currently maintain our own codebase, however for a new project we would like to build upon an existing library.
Yours looks like a good place to either fork or, better yet help extending.
Would you be open for that? And what is your current license model?

Kind regards,
Jelle

**Comment by AchievedOwner** [comment]
Hello @JelleHissink 
Thanks for your fork. It's a good idea to extend with the members from Fomatic-UI.
About the license, in my thinking just follow the same as Fomatic-UI, MIT is ok.
And I will push the license on later.

**Comment by JelleHissink** [comment]
I saw... great to hear.
